using BepInEx.Configuration;
using System;
using System.Collections.Generic;
using System.Text;

namespace DecayMode
{
    public static class ModConfig
    {
        public static ConfigFile File;

        private static ConfigEntry<ConfigList<string>> EnemiesWithDecayOnSpawnEntry;
        private static ConfigEntry<ConfigList<string>> EnemiesIgnoredForDecayEntry;

        private static ConfigEntry<int> DecayChanceEntry;
        private static ConfigEntry<bool> IgnoreWitheringEntry;
        private static ConfigEntry<bool> HideDecayEnemyEntry;

        private static ConfigEntry<DecayModeEnemyPool> EnemyPoolEntry;
        private static ConfigEntry<ConfigDictionary<string, DecayModeEnemyPool>> EnemyPoolExceptionsEntry;
        private static ConfigEntry<string> ModdedMassSpawnPoolEntry;
        private static ConfigEntry<string> ModdedRandomSpawnPoolEntry;
        private static ConfigEntry<string> ModdedTransformPoolEntry;
        private static ConfigEntry<ConfigList<string>> TargetUnitTypesEntry;
        private static ConfigEntry<ConfigList<string>> CustomEnemyPoolEntry;

        public static ConfigList<string> EnemiesWithDecayOnSpawn => EnemiesWithDecayOnSpawnEntry.Value;
        public static ConfigList<string> EnemiesIgnoredForDecay => EnemiesIgnoredForDecayEntry.Value;

        public static int DecayChance => DecayChanceEntry.Value;
        public static bool IgnoreWithering => IgnoreWitheringEntry.Value;
        public static bool HideDecayEnemy => HideDecayEnemyEntry.Value;

        public static DecayModeEnemyPool EnemyPool => EnemyPoolEntry.Value;
        public static ConfigDictionary<string, DecayModeEnemyPool> EnemyPoolExceptions => EnemyPoolExceptionsEntry.Value;
        public static string ModdedMassSpawnPool => ModdedMassSpawnPoolEntry.Value;
        public static string ModdedRandomSpawnPool => ModdedRandomSpawnPoolEntry.Value;
        public static string ModdedTransformPool => ModdedTransformPoolEntry.Value;
        public static ConfigList<string> TargetUnitTypes => TargetUnitTypesEntry.Value;
        public static ConfigList<string> CustomEnemyPool => CustomEnemyPoolEntry.Value;

        public static void Init()
        {
            ConfigTools.RegisterListConfigType<string>();
            ConfigTools.RegisterDictionaryConfigType<string, DecayModeEnemyPool>();

            EnemiesWithDecayOnSpawnEntry    = File.Bind("DecayMode", "EnemiesWithDecayOnSpawn", new ConfigList<string>()
            {
                "NextOfKin_EN",
                "Moone_EN",

                "HeavensGateBlue_BOSS",
                "HeavensGatePurple_BOSS",
                "HeavensGateRed_BOSS",
                "HeavensGateYellow_BOSS",

                "OsmanLeft_BOSS",
                "OsmanRight_BOSS",

                "Bronzo_MoneyPile_EN",
                "BronzoExtra_EN",
                "Bronzo_Bananas_Mean_EN"
            }, "The IDs of enemies that get decay even when spawned mid-combat, separated by commas.");
            EnemiesIgnoredForDecayEntry     = File.Bind("DecayMode", "EnemiesIgnoredForDecay", new ConfigList<string>()
            {
                "OsmanSinnoks_BOSS",

                "Bronzo1_EN",
                "Bronzo2_EN",
                "Bronzo3_EN",
                "Bronzo4_EN",
                "Bronzo5_EN",
            }, "The IDs of enemies that are completely unaffected by Decay Mode, separated by commas.\nNOTE: If Bronzo's first or fourth phases are affected by Decay Mode, defeating them will softlock the fight. It's recommended to always leave them in this list.");

            DecayChanceEntry                = File.Bind("DecayMode.DecayParameters", "DecayChance", 100, "The chance for the Decay generated by Decay Mode to spawn an enemy.");
            IgnoreWitheringEntry            = File.Bind("DecayMode.DecayParameters", "IgnoreWithering", false, "If true, the Decay generated by Decay Mode will not spawn an enemy if the enemy it's on dies from Withering.");
            HideDecayEnemyEntry             = File.Bind("DecayMode.DecayParameters", "HideDecayEnemy", false, "If true, the Decay generated by Decay Mode will not have the name of the enemy it spawns in its description.");

            EnemyPoolEntry                  = File.Bind("DecayMode.EnemyPool", "EnemyPool", DecayModeEnemyPool.Sepulchre, "The enemy pool that Decay Mode will choose the enemies for Decay from.");
            EnemyPoolExceptionsEntry        = File.Bind("DecayMode.EnemyPool", "EnemyPoolExceptions", new ConfigDictionary<string, DecayModeEnemyPool>()
            {
                ["Bronzo_MoneyPile_EN"] = DecayModeEnemyPool.Bronzo,
                ["BronzoExtra_EN"] = DecayModeEnemyPool.Bronzo,
                ["Bronzo_Bananas_Mean_EN"] = DecayModeEnemyPool.Bronzo
            }, "Enemies that will use different enemy pools for their Decay. The key (enemy ID) and the value (the enemy pool its Decay) of an individual key-value pair are separated by an equals sign. All the key-value pairs are separated by commas.");
            ModdedMassSpawnPoolEntry        = File.Bind("DecayMode.EnemyPool", "ModdedMassSpawnPool", "", "The ID of the modded SpawnMassivelyEverywhereUsingHealthEffect enemy pool that the ModdedMassSpawnPool enemy pool type draws from.");
            ModdedRandomSpawnPoolEntry      = File.Bind("DecayMode.EnemyPool", "ModdedRandomSpawnPool", "", "The ID of the modded SpawnRandomEnemyAnywhereEffect enemy pool that the ModdedRandomSpawnPool enemy pool type draws from.");
            ModdedTransformPoolEntry        = File.Bind("DecayMode.EnemyPool", "ModdedTransformPool", "", "The ID of the modded CasterRandomTransformationEffect enemy pool that the ModdedTransformPool enemy pool type draws from.");
            TargetUnitTypesEntry            = File.Bind("DecayMode.EnemyPool", "TargetUnitTypes", new ConfigList<string>(), "All enemies that have any of these UnitTypes will be in the enemy pool for the EnemiesWithUnitType enemy pool type. These UnitTypes are separated by commas.");
            CustomEnemyPoolEntry            = File.Bind("DecayMode.EnemyPool", "CustomEnemyPool", new ConfigList<string>(), "The IDs of enemies that will be in the enemy pool for the CustomEnemyPool enemy pool type, separated by commas.");
        }
    }
}
